### ISSUE TITLE
[error]: npm install from github

### ISSUE THREAD

**Issue by djavrell** [ng-bootstrap/core#173]
hello,

I try to install ng-bootstrap as npm module but i've got an error.
I don't know if the reason is beacause the hooks file have a ".sample" at the end or not.

```
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '.git/hooks/commit-msg'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.writeFileSync (fs.js:1224:33)
    at Object.<anonymous> (~/Documents/roadventure/roadventure-web/node_modules/angular-ng-bootstrap/misc/validate-commit.install.js:10:6)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Linux 4.4.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/sbin/npm" "install" "git://github.com/ng-bootstrap/core.git"
npm ERR! node v5.8.0
npm ERR! npm  v3.8.5
npm ERR! code ELIFECYCLE
```

ps: have you plan too put it on npm ?

thx for your help

**Comment by Foxandxss** [comment]
You shouldn't be trying to even use this repository yet. It is really WIP, half baked and not even alpha.

We will release it on npm when we have something that can be consumed.
