### ISSUE TITLE
Positioning: test are failing on Chrome

### ISSUE THREAD

**Issue by pkozlowski-opensource** [ng-bootstrap/core#321]
At least in my env (Ubuntu, Chrome 51.0.2700.0 64-bit). Tests are fine on FFox.

When a test is failing calculations are off, ex.:

> Chrome 51.0.2700 (Linux 0.0.0) Positioning should calculate the element offset FAILED
	Expected 204 to be 100.
	    at eval (/home/pk/work/gitrepos/gh/pkozlowski-opensource/core/temp/util/positioning.spec.js:39:40 <- /source/util/positioning.spec.ts:48:25)
	    at Object.eval (/home/pk/work/gitrepos/gh/pkozlowski-opensource/core/node_modules/@angular/core/testing/testing.js:98:26)
	    at Object.eval (/home/pk/work/gitrepos/gh/pkozlowski-opensource/core/node_modules/@angular/core/testing/testing.js:110:17)
	Expected 404 to be 300.
	    at eval (/home/pk/work/gitrepos/gh/pkozlowski-opensource/core/temp/util/positioning.spec.js:40:43 <- /source/util/positioning.spec.ts:49:28)
	    at Object.eval (/home/pk/work/gitrepos/gh/pkozlowski-opensource/core/node_modules/@angular/core/testing/testing.js:98:26)
	    at Object.eval (/home/pk/work/gitrepos/gh/pkozlowski-opensource/core/node_modules/@angular/core/testing/testing.js:110:17)

**Comment by RobJacobs** [comment]
@pkozlowski-opensource  I think it may be struggling with adding/removing the test element from the body before/after each test.  Could you try the following in your environment in the positioning.spec.ts to see if it fixes the problem:

1. Remove beforeEach/afterEach methods
2. add: document.body.appendChild(element) to line 30 (before the first test).
3. add: document.body.removeChiled(element) to the 'cleanUp' test
